// <auto-generated />
using System;
using MedicProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace MedicProject.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20201112111519_AddedToken")]
    partial class AddedToken
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("MedicProject.Models.Appointments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("date")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("hour")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("APPOINTMENTS");
                });

            modelBuilder.Entity("MedicProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("RAW(2000)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("RAW(2000)");

                    b.Property<string>("Token")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("cnp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("doctorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("email")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("firstName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("isApproved")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("isMedic")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("lastName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("photo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("doctorId");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("MedicProject.Models.Appointments", b =>
                {
                    b.HasOne("MedicProject.Models.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicProject.Models.User", b =>
                {
                    b.HasOne("MedicProject.Models.User", "doctor")
                        .WithMany("Pacients")
                        .HasForeignKey("doctorId");
                });
#pragma warning restore 612, 618
        }
    }
}
