//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mobile.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age:.
        /// </summary>
        internal static string AgeProfile {
            get {
                return ResourceManager.GetString("AgeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t introduced your birthday..
        /// </summary>
        internal static string AlertBirthday {
            get {
                return ResourceManager.GetString("AlertBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to try again?.
        /// </summary>
        internal static string AlertChange {
            get {
                return ResourceManager.GetString("AlertChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You introduced an invalid personal identification number..
        /// </summary>
        internal static string AlertCnp {
            get {
                return ResourceManager.GetString("AlertCnp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is invalid..
        /// </summary>
        internal static string AlertEmail {
            get {
                return ResourceManager.GetString("AlertEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t complete all the fields..
        /// </summary>
        internal static string AlertFillField {
            get {
                return ResourceManager.GetString("AlertFillField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You introduced an invalid personal identification number.
        /// </summary>
        internal static string AlertPIN {
            get {
                return ResourceManager.GetString("AlertPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your passwords don&apos;t match..
        /// </summary>
        internal static string AlertPwdMatch {
            get {
                return ResourceManager.GetString("AlertPwdMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is not strong enough.
        /// </summary>
        internal static string AlertPwdNotStrong {
            get {
                return ResourceManager.GetString("AlertPwdNotStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password too short. It should be at least 6 characters long..
        /// </summary>
        internal static string AlertPwdShort {
            get {
                return ResourceManager.GetString("AlertPwdShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved..
        /// </summary>
        internal static string AllRightsRes {
            get {
                return ResourceManager.GetString("AllRightsRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send another email.
        /// </summary>
        internal static string AnotherEmail {
            get {
                return ResourceManager.GetString("AnotherEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointment could not be saved..
        /// </summary>
        internal static string AppNotSAved {
            get {
                return ResourceManager.GetString("AppNotSAved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        internal static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appts.
        /// </summary>
        internal static string AppointmentsShort {
            get {
                return ResourceManager.GetString("AppointmentsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointment has been saved..
        /// </summary>
        internal static string AppSavedMess {
            get {
                return ResourceManager.GetString("AppSavedMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date is available..
        /// </summary>
        internal static string AvailableDate {
            get {
                return ResourceManager.GetString("AvailableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check availability.
        /// </summary>
        internal static string CheckAvailability {
            get {
                return ResourceManager.GetString("CheckAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an appointment date.
        /// </summary>
        internal static string ChooseDate {
            get {
                return ResourceManager.GetString("ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a doctor.
        /// </summary>
        internal static string ChooseDoctor {
            get {
                return ResourceManager.GetString("ChooseDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Identification Number.
        /// </summary>
        internal static string Cnp {
            get {
                return ResourceManager.GetString("Cnp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your inbox. An email with a code has been send to this address. Write the code in the box below..
        /// </summary>
        internal static string CodeInstructions {
            get {
                return ResourceManager.GetString("CodeInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string ConfPwd {
            get {
                return ResourceManager.GetString("ConfPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        internal static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete pacient.
        /// </summary>
        internal static string DeletePacient {
            get {
                return ResourceManager.GetString("DeletePacient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in with the given data.
        ///Look through the past and future appointments in the Appt page. You can delete future appointments by tapping on the chosen one and selecting the delete button.
        ///Look through the pacients in the Pacients page delete the ones you want by tapping one and tapping the delete button.
        ///Look through the new request and accept or decline pacients.
        ///Verify your profile data in the Profile Page and change it if you want by clicking the settings icon.
        ///On the settings page you will be able [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DoctorGuide {
            get {
                return ResourceManager.GetString("DoctorGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string EmailProfile {
            get {
                return ResourceManager.GetString("EmailProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t introduced an email.
        /// </summary>
        internal static string EmptyEmail {
            get {
                return ResourceManager.GetString("EmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter code.
        /// </summary>
        internal static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error..
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error. Please try again..
        /// </summary>
        internal static string ErrorTryAgain {
            get {
                return ResourceManager.GetString("ErrorTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit?.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string ForgotPass {
            get {
                return ResourceManager.GetString("ForgotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName:.
        /// </summary>
        internal static string FullNameProfile {
            get {
                return ResourceManager.GetString("FullNameProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to go to main page.
        /// </summary>
        internal static string GoMainPage {
            get {
                return ResourceManager.GetString("GoMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        internal static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brief guide to the application.
        /// </summary>
        internal static string GuideHelp {
            get {
                return ResourceManager.GetString("GuideHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string HasAccount {
            get {
                return ResourceManager.GetString("HasAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hei,.
        /// </summary>
        internal static string Hei {
            get {
                return ResourceManager.GetString("Hei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your code is invalid..
        /// </summary>
        internal static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make appointment.
        /// </summary>
        internal static string MakeAppointment {
            get {
                return ResourceManager.GetString("MakeAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in with the chosen the email and password.
        ///Enter the appointment section, make an appoinment.
        ///Look through the past and future appoinments. You can delete future appointments by tapping and selecting the delete button.
        ///Verify your profile data in the Profile Page and change it if you want by clicking the settings icon.
        ///On the settings page you will be able to update your data.
        ///Verify your profile data and change it if you want by clicking the settings icon..
        /// </summary>
        internal static string PacientAcceptGuide {
            get {
                return ResourceManager.GetString("PacientAcceptGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your family doctor.
        ///Register with your personal data. 
        ///Wait for the doctor to accept your request..
        /// </summary>
        internal static string PacientRegisterGuide {
            get {
                return ResourceManager.GetString("PacientRegisterGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        internal static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        internal static string PhoneProfile {
            get {
                return ResourceManager.GetString("PhoneProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN.
        /// </summary>
        internal static string PIN {
            get {
                return ResourceManager.GetString("PIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN:.
        /// </summary>
        internal static string PINProfile {
            get {
                return ResourceManager.GetString("PINProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of birth.
        /// </summary>
        internal static string PlaceOfBirth {
            get {
                return ResourceManager.GetString("PlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password should contain at least one digit..
        /// </summary>
        internal static string PwdDigit {
            get {
                return ResourceManager.GetString("PwdDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password should contain at least one lowercase character..
        /// </summary>
        internal static string PwdLowerCharacter {
            get {
                return ResourceManager.GetString("PwdLowerCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password strength is medium..
        /// </summary>
        internal static string PwdMedium {
            get {
                return ResourceManager.GetString("PwdMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have lost your password, it can be recovered by taping on the &quot;Forgetten password&quot; text from the Log in page.
        ///Once you get there you have to introduce your account email and tap on the &quot;Send email button&quot;. An email 
        ///containing a code will be sent to you, you have to introuce the code and the new password..
        /// </summary>
        internal static string PwdRecoveryGuide {
            get {
                return ResourceManager.GetString("PwdRecoveryGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is strong..
        /// </summary>
        internal static string PwdStrong {
            get {
                return ResourceManager.GetString("PwdStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password should contain at least one upper character..
        /// </summary>
        internal static string PwdUpperCharacter {
            get {
                return ResourceManager.GetString("PwdUpperCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is very strong..
        /// </summary>
        internal static string PwdVeryStrong {
            get {
                return ResourceManager.GetString("PwdVeryStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is weak..
        /// </summary>
        internal static string PwdWeak {
            get {
                return ResourceManager.GetString("PwdWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is recovered..
        /// </summary>
        internal static string RecoverAccount {
            get {
                return ResourceManager.GetString("RecoverAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery password.
        /// </summary>
        internal static string RecoveryPwd {
            get {
                return ResourceManager.GetString("RecoveryPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your registration is not successful. Please try again :).
        /// </summary>
        internal static string RegistrationNotSucceed {
            get {
                return ResourceManager.GetString("RegistrationNotSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your registration is successful. Please wait for the doctor to accept your request..
        /// </summary>
        internal static string RegistrationSucceed {
            get {
                return ResourceManager.GetString("RegistrationSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        internal static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error or invalid email..
        /// </summary>
        internal static string ResetPwdEmail {
            get {
                return ResourceManager.GetString("ResetPwdEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save the changes?.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email.
        /// </summary>
        internal static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        internal static string SetPwd {
            get {
                return ResourceManager.GetString("SetPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up!.
        /// </summary>
        internal static string SingUp {
            get {
                return ResourceManager.GetString("SingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful reset..
        /// </summary>
        internal static string SuccessfulReset {
            get {
                return ResourceManager.GetString("SuccessfulReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful registration.
        /// </summary>
        internal static string SucRegistration {
            get {
                return ResourceManager.GetString("SucRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date is not available. .
        /// </summary>
        internal static string UnavailableDate {
            get {
                return ResourceManager.GetString("UnavailableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Code.
        /// </summary>
        internal static string ValidateCode {
            get {
                return ResourceManager.GetString("ValidateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert the code sent to you by email....
        /// </summary>
        internal static string ValidateCodeDesc {
            get {
                return ResourceManager.GetString("ValidateCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify code.
        /// </summary>
        internal static string VerifyCode {
            get {
                return ResourceManager.GetString("VerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
